### PR TITLE
Only calculate checksums, when there are files to monitor.

### LINKED ISSUE #2775: [BUG] DMS fails to start, when SMTP_ONLY=1 is used and no user is present.
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postfix

### What happened and when does this occur?

```Markdown
Starting DMS fails with SMTP_ONLY=1 and no user added.

The startup stops/hangs at

mailserver  | [   INF   ]  Welcome to docker-mailserver 11.1.0
mailserver  | [   INF   ]  Initializing setup
mailserver  | [   INF   ]  Checking configuration
mailserver  | [   INF   ]  Configuring mail server
mailserver  | [ WARNING ]  !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT
```

### What did you expect to happen?

```Markdown
Correct startup of DMS.
```

### How do we replicate the issue?

```Markdown
1. Configure SMTP_ONLY=1
2. Do NOT add any additional configuration files (Not adding a user)
3. Start DMS
...
```

### DMS version

v11.1.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
Unmodified example docker-compose.yml
```

### Relevant log output

_No response_

### Other relevant information

_No response_

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

_No response_

### PR DESCRIPTION
**Pull request by casperklein**
# Description

This PR fixes a bug, where checksum calculation was done/tried, when there were no files to monitor.

Fixes #2775

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: target/scripts/helpers/change-detection.sh [hunk 1]
```diff
@@ -73,5 +73,5 @@ function _monitored_files_checksums
   do
     [[ -f "${FILE}" ]] && CHANGED_FILES+=("${FILE}")
   done
-  sha512sum -- "${CHANGED_FILES[@]}"
+  [[ ${#CHANGED_FILES[@]} -ne 0 ]] && sha512sum -- "${CHANGED_FILES[@]}"
```
Comment (georglauterbach) [inline target/scripts/helpers/change-detection.sh:76]: Can we have a `return 0` afterwards please?:) otherwise this function may return with exit code 1, which could be undesired if we want to add `set -eE` in the future:)

Comment (casperklein) [reply target/scripts/helpers/change-detection.sh:76]: I'll wrap it within an if statement.

**Comment by casperklein** [comment]
Not sure, why [this](https://github.com/docker-mailserver/docker-mailserver/actions/runs/3077162623/jobs/4971833939#step:5:225) test failed. But I don't think it was related to my changes. I've started the tests again.

**Comment by georglauterbach** [comment]
`set -u` complains about `CHANGED_FILES` not being set even though it was `declare`d earlier? That is weird..

**Comment by casperklein** [comment]
See here:

```bash
set -u
declare -a foo
echo $foo
-bash: foo: unbound variable
```

However, I am not sure anymore if there is even 'set -u' in place, that caused the failing tests. That may be a wrong assumption from me earlier.

https://github.com/docker-mailserver/docker-mailserver/pull/2776/commits/f72bc78678cbb39523f55404d768ddc4f343ab08 fixed it. But I don't know exactly why 🤷

**Review by polarathene — APPROVED** [review]

**Review by georglauterbach — APPROVED** [review]
The thing with the array and ´set -u` is pretty weird .. :D
