### PR TITLE
fix: Apply SELinux security context after moving to mail-state

### LINKED ISSUE #3887: bug report: SELinux incompatibility using named volumes
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

On my FedoraCoreOS host, SELinux is enabled ("enforcing") by default, and I run into some issues with docker-mailserver on my setup, using named volumes (see config below). Initial startup is good, but when the container is recreated (e.g. `docker compose up -d --force-recreate mail`) it breaks (see logs below).

I understand this might be out of scope as it concerns SELinux, but would still like to check if this is not somehow an issue with the image, as it only affects 1 of the volumes (`mail-state`).

Workaround where it doesn't break:
- Disabling SELinux system wide (`sudo setenforce 0`)
- Running the container privileged (`privileged: true` in compose.yaml)
- Disabling SELinux for the container (`security_opt: - label:disable` in compose.yaml)

Interestingly, adding bind option `:z` or `:Z` to the mounts (which is the suggested solution in many places) does not help; it looks like it's not used/allowed for named volumes (only bind mounts) which is why compose warns about that in some of its commands.

Other than disabling SELinux I don't have a solution for this. I can see the directories within `mail-state` are improperly labeled and I also cannot access them using docker exec. However, other volumes like `mail-data` also get some automatically created dirs, but they are labeled `system_u:object_r:container_file_t:s0` and can be accessed without issues:

```sh
# ls -Z /var/mail /var/mail-state | cat
/var/mail:
system_u:object_r:container_file_t:s0 example.com

/var/mail-state:
system_u:object_r:container_file_t:s0:c1022,c1023 lib-dovecot
system_u:object_r:container_file_t:s0:c1022,c1023 lib-fail2ban
system_u:object_r:container_file_t:s0:c1022,c1023 lib-logrotate
system_u:object_r:container_file_t:s0:c1022,c1023 lib-postfix
system_u:object_r:container_file_t:s0:c1022,c1023 lib-redis
system_u:object_r:container_file_t:s0:c1022,c1023 lib-rspamd
system_u:object_r:container_file_t:s0:c1022,c1023 spool-postfix
```

Anything special about the way mail-state is initially provisioned that makes it behave in this way? Any clue why I don't have this issue with the other named volumes?

### 👟 Reproduction Steps

_No response_

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

FedoraCoreOS 39 x86_64

### ⚙️ Container configuration files

```yml
volumes:
  # ...
  letsencrypt:
    name: letsencrypt
  mail-data:
    name: mail-data
  mail-state:
    name: mail-state
  mail-logs:
    name: mail-logs
  mail-config:
    name: mail-config

services:
  # ...
  mail:
    container_name: mail
    image: mailserver/docker-mailserver
    hostname: ######
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - '25:25'
      - '465:465'
      - '587:587'
      - '993:993'
    volumes:
      - mail-data:/var/mail
      - mail-state:/var/mail-state
      - mail-logs:/var/log/mail
      - mail-config:/tmp/docker-mailserver
      - letsencrypt:/etc/letsencrypt
    environment:
      ENABLE_RSPAMD: 1
      ENABLE_FAIL2BAN: 1
      ENABLE_CLAMAV: 0
      ENABLE_OPENDMARC: 0
      ENABLE_OPENDKIM: 0
      ENABLE_POLICYD_SPF: 0
      ENABLE_AMAVIS: 0
      ENABLE_SPAMASSASSIN: 0
      ENABLE_UPDATE_CHECK: 0
      DOVECOT_MAILBOX_FORMAT: mdbox
      SSL_TYPE: letsencrypt
      SPOOF_PROTECTION: 1
      MOVE_SPAM_TO_JUNK: 1
      MARK_SPAM_AS_READ: 1
      RSPAMD_LEARN: 1
      TZ: Europe/Amsterdam
```

### 📜 Relevant log output

```Text
[   INF   ]  Welcome to docker-mailserver v13.3.1
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
chown: cannot read directory '/var/mail-state/lib-rspamd': Permission denied
chown: cannot read directory '/var/mail-state/lib-redis': Permission denied
chown: cannot read directory '/var/mail-state/lib-logrotate': Permission denied
chown: cannot read directory '/var/mail-state/lib-postfix': Permission denied
chown: cannot read directory '/var/mail-state/spool-postfix': Permission denied
chown: changing ownership of '/var/mail-state/spool-postfix': Permission denied
chgrp: cannot access '/var/mail-state/spool-postfix/maildrop': Permission denied
chgrp: cannot access '/var/mail-state/spool-postfix/public': Permission denied
chmod: cannot access '/var/mail-state/spool-postfix/maildrop': Permission denied
chmod: cannot access '/var/mail-state/spool-postfix/public': Permission denied
rm: cannot remove '/var/mail-state/spool-postfix/dev': Permission denied
rm: cannot remove '/var/mail-state/spool-postfix/etc': Permission denied
rm: cannot remove '/var/mail-state/spool-postfix/lib': Permission denied
rm: cannot remove '/var/mail-state/spool-postfix/pid': Permission denied
rm: cannot remove '/var/mail-state/spool-postfix/usr': Permission denied
rm: cannot remove '/var/mail-state/spool-postfix/private/auth': Permission denied
[   INF   ]  Starting daemons
[   INF   ]  ###### is up and running
Feb 12 21:36:12 mail postfix[858]: fatal: chdir(/var/spool/postfix): Permission denied
Feb 12 21:36:17 mail postfix[983]: fatal: chdir(/var/spool/postfix): Permission denied
Feb 12 21:36:22 mail postfix[1086]: fatal: chdir(/var/spool/postfix): Permission denied
...
```

### Improvements to this form?

_No response_

### PR DESCRIPTION
**Pull request by robbertkl**
# Description

After `setup.d/mail_state.sh` moves files/dirs from the container itself to `/var/mail-state`, they retains their SELinux security context labels, which are bound to the current container. When using named volumes, this leads to the files/dirs becoming inaccessible.

This PR lets the setup script apply the security context from the mail-state directory after moving, so they are still accessible when a new container is created that re-uses a named volume. The result is that the moved files will have the same security context as if they were created by the script.

This also explains the issue only occurs with the mail-state volume. In the other volumes only new files are created, instead of files being moved.

Fixes #3887 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary, I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] **I have added information about changes made in this PR to `CHANGELOG.md`**

### CODE REVIEW

**Comment by casperklein** [comment]
LGTM 👍

Can this have any unwanted side-effects/problems on systems, not using SELinux security context?

**Comment by robbertkl** [comment]
I've added ignoring the exit status (in case the scripts use `set -e`) and discarding stderr so there won't be any error message for non SELinux systems.

If the system supports SELinux but it's "Permissive" instead of "Enforcing", the `chcon` isn't really needed for it to work, although it prevents a lot of audit messages so is still nice to have. On a system without SELinux (I've tested on an old RancherOS host with linux 4.14) `chcon` fails and outputs an error; it doesn't do any harm (so shouldn't have any side effects), but I've now ignored the error so it doesn't pollute the container log.

File: target/scripts/startup/setup.d/mail_state.sh [hunk 1]
```diff
@@ -48,6 +48,9 @@ function _setup_save_states() {
         _log 'trace' "Moving ${SERVICEFILE} to ${DEST}"
         # Empty volume was mounted, or new content from enabling a feature ENV:
         mv "${SERVICEFILE}" "${DEST}"
+        # Apply SELinux security context to match the state directory, so access
+        # is not restricted to the current running container:
+        chcon -R --reference="${STATEDIR}" "${DEST}" 2> /dev/null || true
```
Comment (casperklein) [inline target/scripts/startup/setup.d/mail_state.sh:53]:
```suggestion
        chcon -R --reference="${STATEDIR}" "${DEST}" 2>/dev/null || true
```

File: target/scripts/startup/setup.d/mail_state.sh [hunk 2]
```diff
@@ -69,6 +72,9 @@ function _setup_save_states() {
         _log 'trace' "Moving contents of ${SERVICEDIR} to ${DEST}"
         # Empty volume was mounted, or new content from enabling a feature ENV:
         mv "${SERVICEDIR}" "${DEST}"
+        # Apply SELinux security context to match the state directory, so access
+        # is not restricted to the current running container:
+        chcon -R --reference="${STATEDIR}" "${DEST}" 2> /dev/null || true
```
Comment (casperklein) [inline target/scripts/startup/setup.d/mail_state.sh:77]:
```suggestion
        chcon -R --reference="${STATEDIR}" "${DEST}" 2>/dev/null || true
```

**Review by casperklein — CHANGES_REQUESTED** [review]
Two changes to align with the style elsewhere used in DMS.

**Comment by robbertkl** [comment]
Thanks, fixed!

**Review by casperklein — DISMISSED** [review]

**Comment by robbertkl** [comment]
@polarathene Just curious, did you assign me to update my branch? Just did and unassigned myself again, hope that's ok.

**Comment by georglauterbach** [comment]
I re-assigned you; this makes finding PRs for maintainers easier.

File: CHANGELOG.md [hunk 3]
```diff
@@ -82,6 +82,7 @@ The most noteworthy change of this release is the update of the container's base
   - `RELAY_HOST` ENV no longer enforces configuring outbound SMTP to require credentials. Like `DEFAULT_RELAY_HOST` it can now configure a relay where credentials are optional.
   - Restarting DMS should not be required when configuring relay hosts without these ENV, but solely via `setup relay ...`, as change detection events now apply relevant Postfix setting changes for supporting credentials too.
 - Rspamd configuration: Add a missing comma in `local_networks` so that all internal IP addresses are actually considered as internal ([#3862](https://github.com/docker-mailserver/docker-mailserver/pull/3862))
+- Ensure correct SELinux security context labels for files and directories moved to mail-state during setup ([#3890](https://github.com/docker-mailserver/docker-mailserver/pull/3890))
```
Comment (polarathene) [inline CHANGELOG.md:85]:
```suggestion
- Ensure correct SELinux security context labels for files and directories moved to the mail-state volume during setup ([#3890](https://github.com/docker-mailserver/docker-mailserver/pull/3890))
```

**Review by polarathene — CHANGES_REQUESTED** [review]
I'll apply this.

**Review by polarathene — APPROVED** [review]
LGTM! Like @casperklein I don't have the SELinux expertise to provide much feedback.

I'd merge but not sure if @georglauterbach wants to block for their own review.

**Review by casperklein — APPROVED** [review]

**Comment by georglauterbach** [comment]
Go ahead and merge, not time to review this one :)
