### PR TITLE
Enhancement for function _setup_postfix_sasl fixing #1796 & More

### LINKED ISSUE #1796: [BUG] SASL is enabled with ENABLE_SASLAUTHD=0 but only when SMTP_ONLY=1
# Bug Report

I believe this is the same as #1687. I do not want SASL.

Using `ENABLE_SASLAUTHD=0` and `SMTP_ONLY=1` results in the following log error (and `could not connect to this SMTP server` error in Apple Mail).

This is the relevant log error:

```
Feb  7 14:15:31 mailer-ams postfix/submission/smtpd[892]: warning: SASL: Connect to private/auth failed: Connection refused
Feb  7 14:15:31 mailer-ams postfix/submission/smtpd[892]: fatal: no SASL authentication mechanisms
```

## Context

Fresh installation.

### What is affected by this bug?

Using SMTP.

### When does this occur?

Every time.

### How do we replicate the issue?

I follow the [default installation instructions](https://github.com/docker-mailserver/docker-mailserver#get-the-tools).

Besides adding domain and hostname to `.env`, this is what I edit in `mailserver.env`:

```
SMTP_ONLY=1
ONE_DIR=1
PERMIT_DOCKER=host
SSL_TYPE=manual
SSL_CERT_PATH=/path/to/fullchain.cer
SSL_KEY_PATH=/path/to/cert.key
```
I keep `ENABLE_SASLAUTHD=0` with its default value.

`docker-compose.yml` only mounts `/path/to/`. https://www.checktls.com is happy with the settings, gives 100% and valid certificate.

# Workaround

Setting `SMTP_ONLY=` (to empty) fixes the issue.

## Your Environment

- version: `docker.io/mailserver/docker-mailserver:latest`
- available RAM: `8GB`
- Docker version: `Docker version 20.10.3, build 48d30b5`

### PR DESCRIPTION
**Pull request by aendeavor**
# Description

SASL is now disabled correctly. The `Dockerfile` has been adjusted to not show the `delaying debconf because apt-utils is not installed` error anymore. `function _misc_save_states` was refactored too as it was in an unacceptable state. Especially proud of the inline variable substitutions that got rid of `echo ... | sed ...`.

Fixes #1796

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or ENVIRONMENT.md or the Wiki)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

---

PS: I like the new template :D

### CODE REVIEW

**Comment by wernerfred** [comment]
> PS: I like the new template :D

🥳 

My hope is that people get motivated providing some more information than they would without it

**Review by wernerfred — APPROVED** [review]
LGTM

File: target/scripts/start-mailserver.sh [hunk 1]
```diff
@@ -1970,42 +1969,45 @@ function misc
...
+      lib/amavis
+      lib/clamav
+      lib/spamassassin
+      lib/fail2ban
+      lib/postgrey
+      lib/dovecot
     )
 
-    for d in "${FILES[@]}"
+    for FILE in "${FILES[@]}"
```
Comment (casperklein) [inline target/scripts/start-mailserver.sh:1992]: FILE should be "local"

File: target/scripts/start-mailserver.sh [hunk 2]
```diff
@@ -1970,42 +1969,45 @@ function misc
 
 function _misc_save_states
 {
-  # consolidate all states into a single directory (`/var/mail-state`) to allow persistence using docker volumes
-  statedir=/var/mail-state
+  # consolidate all states into a single directory (`/var/mail-state`)
+  # to allow persistence using docker volumes
 
-  if [[ ${ONE_DIR} -eq 1 ]] && [[ -d ${statedir} ]]
+  local STATEDIR=/var/mail-state
```
Comment (casperklein) [inline target/scripts/start-mailserver.sh:1975]: Quotes missing. Not necesary, but to keep one standard across the whole file.

STATEDIR="/var/mail-state"

File: target/scripts/start-mailserver.sh (hunk 1 above)
Comment (aendeavor) [reply target/scripts/start-mailserver.sh:1992]: didn't know `for local FILE in ...` was even possible, oder did you mean

``` BASH
local FILE
for FILE in ...
```

which is to the best of my knowledge not needed since `FILE` only exists in the loop. And the FILE I explicitly define in the loop is marked `local`. What did I miss?:)

File: target/scripts/start-mailserver.sh (hunk 2 above)
Comment (aendeavor) [reply target/scripts/start-mailserver.sh:1975]: True. I think this is okay for now, and I will push this with a future commit.

File: target/scripts/start-mailserver.sh (hunk 1 above)
Comment (casperklein) [reply target/scripts/start-mailserver.sh:1992]: I meant the second example from you.

`FILE` is not declared local before it's first usage in line 1992. So at this point, it's global and keeps the value `spool/postfix`.

If you run e.g. `echo $FILE` after the function call, you would get `spool/postfix`.
```
_misc_save_states
echo $FILE
```

Comment (aendeavor) [reply target/scripts/start-mailserver.sh:1992]: I always thought this variable is only valid inside the loop, but I'm not actually surprised that it's not - I guess you can always learn something new.  Bash is still full of surprises.

I will do a follow-up here.
