### PR TITLE
fix: include all files in change detection of Rspamd

### LINKED ISSUE #4397: bug report: [DOC] Rspamd DKIM signing: missing information about the need to restart DMS
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Hi

when using rspamd for DKIM output signing, two steps are involved
1. generating the keys with `docker exec -it <CONTAINER NAME> setup config dkim`
2. add the path to the key to the config file `config/rspamd/override.d/dkim_signing.conf`

When running step 1 at the end rspamd is restarted _(which may be necessary for dkim input verification)_ but doc is missing the information that after step 2 the container needs to be restarted.

I think restarting rspamd only is not enough because it doesn't not update `/etc/rspamd/override.d/dkim_signing.conf` inside the container.

If this issue is pertinent, I can propose a PR to update the doc.

### 👟 Reproduction Steps

- add a new mailbox with a new domain
- generate its DKIM key with the `setup` tool
- add the path to the key inside `config/rspamd/override.d/dkim_signing.conf`
- send a mail from this new mailbox to the outside and verify if it's DKIM-signed
- 

### 🐋 DMS Version

v15.0

### 💻 Operating System and Architecture

Debian 12.9, amd64

### ⚙️ Container configuration files

```yml

```

### 📜 Relevant log output

```Text

```

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

Include `*.conf` files when checking for changes in the Rspamd configuration.

Fixes #4397

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary, I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] **I have added information about changes made in this PR to `CHANGELOG.md`**

### CODE REVIEW

File: target/scripts/helpers/change-detection.sh [hunk 1]
```diff
@@ -43,7 +43,7 @@ function _monitored_files_checksums() {
 
     # Check whether Rspamd is used and if so, monitor it's changes as well
     if [[ ${ENABLE_RSPAMD} -eq 1 ]] && [[ -d ${RSPAMD_DMS_D} ]]; then
-      readarray -d '' STAGING_FILES_RSPAMD < <(find "${RSPAMD_DMS_D}" -type f -name "*.sh" -print0)
+      readarray -d '' STAGING_FILES_RSPAMD < <(find "${RSPAMD_DMS_D}" -type f \( -name '*.sh' -or -name '*.conf' \) -print0)
```
Comment (polarathene) [inline target/scripts/helpers/change-detection.sh:46]: What `.sh` files are be monitored? Nothing stood out from the docs or related `check-for-changes.sh` rspamd section.

Comment (georglauterbach) [reply target/scripts/helpers/change-detection.sh:46]: I think it's only `*.conf` files, really. I don't even know why we started off with `*.sh` in the first place?

Comment (polarathene) [reply target/scripts/helpers/change-detection.sh:46]: > I don't even know why we started off with `*.sh` in the first place?

You're the one [who contributed it](https://github.com/docker-mailserver/docker-mailserver/pull/3599/files#r1371483052) 😆 (_[the specific commit](https://github.com/docker-mailserver/docker-mailserver/pull/3599/commits/aa86e6e96ba76af94fbe877002f210ccb556d0ce), and linked comment reference don't provide context to the `.sh` relevance_)

This was back in Oct 2023 (_for [DMS v13 in Nov 2023](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v13.0.0)_), I don't think @casperklein or myself were particularly thorough with reviews for rspamd beyond basics there as you were iterating through initial Rspamd support (_introduced since [DMS v12 in April 2023](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v12.0.0)_).

If you're sure that there was some mistake with `.sh` there, or some change where we no longer rely upon it, perhaps it can be dropped for `15.0.1` release too 🤔 It is just change detection support for something that shouldn't realistically be changing much once deployed in production, so I think it'd be safe to drop it even if you're not sure why you added it.

File: CHANGELOG.md [hunk 2]
```diff
@@ -22,6 +22,7 @@ All notable changes to this project will be documented in this file. The format
 
 - **Internal:**
   - Minor improvements to `_install_utils()` in `packages.sh` ([#4376](https://github.com/docker-mailserver/docker-mailserver/pull/4376))
+  - all custom files are now included when checking for changes in the Rspamd configuration ([#4418](https://github.com/docker-mailserver/docker-mailserver/pull/4418))
```
Comment (polarathene) [inline CHANGELOG.md:25]:
```suggestion
  - Change detection support for Rspamd now monitors all files at the rspamd Config Volume directory ([#4418](https://github.com/docker-mailserver/docker-mailserver/pull/4418))
```

**Review by polarathene — APPROVED** [review]

**Comment by polarathene** [comment]
Chore or fix? 🤔
